name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch repository
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: ./dispath.sh
