name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch repository
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: curl -X POST -H "Authorization: token $MY_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" --data '{\"event_type\": \"test-hello\"}' https://api.github.com/repos/yykaoruko/rukolog/dispatches
