name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch repository
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
        MY_URL: ${{secrets.MY_URL}}
      run: curl -X POST ${MY_URL}
